auto: false
name: MISDAY
subtitle: Developer
url: http://www.misday.com
authors: Wenhui Wang

pygments: true

paginate: 4
paginate_path: "/page:num"

relative_permalinks: true
permalink: "/:categories/:title/"

exclude: [CNAME, npm-debug.log, node_modules]

google_analytics: UA-0000-00
