auto: false
name: LASACHA
subtitle: lasacha
url: http://www.lasacha.com
authors: Vincent Wang (vin@misday.com)

pygments: true

paginate: 4
paginate_path: "/page:num"

relative_permalinks: true
permalink: "/:categories/:title/"

exclude: [CNAME, npm-debug.log, node_modules]

google_analytics: UA-28333273-1
